FROM postgres:15

WORKDIR /docker-entrypoint-initdb.d

COPY initdb/08_02_2025.sql /docker-entrypoint-initdb.d/

CMD ["sh", "-c", "psql postgresql://postgres:root@postgres:5432/postgres -f /docker-entrypoint-initdb.d/08_02_2025.sql"]
