name: CI/CD Pipeline - Spring Boot Docker + PostgreSQL Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot application
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Spring Boot app image
      - name: Build and push Spring Boot Docker image
        run: |
          docker build -t tmachinya/shaz-app:latest .
          docker push tmachinya/shaz-app:latest

      # Build and push Postgres DB init image
      - name: Build and push DB init Docker image
        run: |
          docker build -t tmachinya/postgres-db-init:latest -f Dockerfile.db-init .
          docker push tmachinya/postgres-db-init:latest

      # Set up kubectl for deploying to local Kubernetes cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Apply Kubernetes manifests (Postgres, Spring Boot, DB Init Job)
      - name: Apply Kubernetes deployments
        run: |
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/springboot-deployment.yaml
          kubectl apply -f k8s/postgres-init-job.yaml
          kubectl wait --for=condition=complete job/postgres-init-job --timeout=180s

      # Optional: Clean up the init job after completion (keeps cluster clean)
      - name: Clean up DB init job
        run: kubectl delete job postgres-init-job || true

      - name: Set KUBECONFIG environment variable (Windows)
        shell: pwsh
        run: |
          echo "KUBECONFIG=C:/Users/user/.kube/config" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Verify Kubernetes cluster connection
        run: kubectl cluster-info
