name: build-deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot app
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t tmachinya/shaz-app:latest .

      - name: Push Docker image
        run: docker push tmachinya/shaz-app:latest

      - name: Set up kubectl
        run: |
          echo "KUBECONFIG=C:/Users/user/.kube/config" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Apply Kubernetes deployments
        shell: cmd
        run: |
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/springboot-deployment.yaml
          kubectl apply -f k8s/postgres-init-job.yaml
          kubectl wait --for=condition=complete job/postgres-init-job --timeout=180s

      - name: Clean up DB init job
        shell: cmd
        run: kubectl delete job postgres-init-job || exit 0

      - name: Wait for Spring Boot rollout
        shell: cmd
        run: kubectl rollout status deployment/springboot

      - name: Port forward Spring Boot service
        shell: cmd
        run: |
          start /b kubectl port-forward service/springboot-service 8080:8080
          timeout /t 5

      - name: Post-deploy health check
        shell: cmd
        run: |
          echo Checking application health...
          set RETRIES=20
          :retry
          curl --fail http://localhost:8080 && echo App is healthy! && exit /b 0
          set /a RETRIES-=1
          if %RETRIES% EQU 0 (
            echo Application health check failed!
            exit /b 1
          )
          timeout /t 10
          goto retry